# Generated by Django 5.1.2 on 2024-11-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_accaunt_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accaunt',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatars/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
